version: '2.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     networks:
       - network
     environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_DATABASE: goapp
       MYSQL_USER: goappuser
       MYSQL_PASSWORD: goapppass
     healthcheck:
       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
       timeout: 5s
       retries: 50
   app:
     build: .
     depends_on:
       db:
          condition: service_healthy
     ports:
       - "8000:8000"
     restart: always
     networks:
       - network
     environment:
       GOAPPPORT: 8000
       GOAPPDBHOST: db
       GOAPPDBPORT: 3306
       GOAPPDBUSER: goappuser
       GOAPPDBPASS: goapppass
       
volumes:
    dbdata:
networks:
  network: